TYPO3-Documentation/DocsTypo3Org-Homepage

Documentation/typo3cms/CheatSheets/Index.rst
The spelling was incorrect, we got a deadlink. After changed additional-documents to AdditionalDocuments the link works again.
=> [TASK] correct Link for "Creating and using mocks in PHPUnit"-CheatSheet

Documentation/Index.rst, Documentation/typo3cms/extensions/Index.rst
The documentation menu has now more logical order (the most important documents are on top)
The button for the TYPO3 Core changelog has been added
=> Reorder documentation menu add changelog button

Documentation/News/2018/Index.rst
The news entry mentions contributions and motivates people to contribute to the docs. The reader should be pointed to information about how to contribute to the docs. This commit message adds a link to this information.
=> Update news entry about TYPO3 explained

Documentation/typo3cms/References/Index.rst
TCA should be written as it is commonly written in menu. Title
capitalization is used in menu. As by our rules, this includes
capitalization of acronyms (if that is how they are spelled)
and special spelling like ViewHelper, TypoScript and TSconfig.
=> Fix spelling of TCA in menu

Documentation/typo3cms/SystemExtensions/Index.rst
We decided to use "system extension" in #typo3-documentation channel.
Also, this is what is being used in the description and in most of
the documenation.
=> Use "system extension" instead of "core extension"

Documentation/typo3cms/GuidesAndTutorials/Index.rst
Should direct everyone directly to README.rst in docker image repo because that is where
they will find a step by step guide.
Related: https://github.com/TYPO3-Documentation/T3DocTeam/issues/58
=> Update links to rendering information in Tutorials and Guides

Documentation/typo3cms/SystemExtensions/Index.rst
Related: https://github.com/TYPO3-Documentation/T3DocTeam/issues/25
=> Add rte_ckeditor docs to list of core extensions

Documentation/About.rst, Documentation/Contribute/Index.rst
In order to reduce duplicate information, the contribute section now directly links
to "Contribute" in "Writing Documentation".
=> Link to contribute chapter in Writing Documentation

Documentation/Index.rst
- will automatically correct spelling
=> Use implicit anchor text for link

Documentation/Index.rst
The proposed order has been added as a comment:
1. Official documentation
2. Community documentation
3. About documenation
4. Teams
It is a little difficult to determine, what is community and what is
"official", but we propose to assume snippets, cheat sheets and external
extensions as "community" documentation.
Additionally, the snippets only contain snippets, so we remove "Tipps
and Howto" in menu title because that is misleading and not helpful.
=> Change order in main menu

Documentation/News/2018/Index.rst
Move Tip to "Writing Documenation"
Related: https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument/pull/63
=> Move tip for rendering extension documentation

Documentation/Settings.cfg, Documentation/typo3cms/GuidesAndTutorials/Index.rst
- The previous recommendation to read in the order listed might have been
good advice in the past but is no longer applicable
- Developers, editors, etc. have different requirements. Some of the guides
and tutorials are not useful at all to some groups.
- The differentiation between tutorials and guides is of little value here.
Some of the guides are actually targeted for beginners.
For this reason, this change groups the manuals by target audience.
Additionally, we refer to (already existing) pages "Next steps"
in "Getting Started Tutorial".
=> Regroup lists of manuals on "Tutorials and Guides"

Documentation/About.rst, Documentation/Tips/DocumentationWriters/DocumentationBuild/Index.rst
Related: https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-RenderTypo3Documentation/pull/3
=> Move "Files in the Build Folder" to Rendering Guide

Documentation/Home/GuidesAndTutorials.rst
=> Remove rendering guide from list

Documentation/Home/GuidesAndTutorials.rst, Documentation/Home/References.rst
- remove Extbase / Fluid Guide from list
- add some manuals to "Outdated"
- move "Localization Guide" to outdated
- add links to manual ViewHelper references
=> Changes to reflect outdated manuals

Documentation/Home/About/News/2019/Index.rst, Documentation/Home/About/News/Index.rst, Documentation/HowToUse/Index.rst, Documentation/Index.rst
- currently we have news on docs.typo3.org and typo3.org
- documenting changes is important, but not every change warrants
a news on typo3.org
- this way, we use similar terminology to core
=> Rename news to "changelog"

Documentation/Home/Contribute.rst, Documentation/Home/Teams.rst, Documentation/Index.rst
- to make docs.typo3.org more user friendly, remove rarely used
menu items
- the "Contribute" menu item is changed to include a link to contribution for core and t3o
=> Remove "Teams" item from menu

Documentation/Home/GuidesAndTutorials.rst
Adding the subheader titles to the menu was awkward - no only because of the similarity of "Getting Started Tutorial" and "Getting Started" section.
This change
- removes the "Getting started" subheader at the top entirely
- changes subheaders to normal text
- preserves existing header labels.
=> Change subheaders to normal to prevent adding them to menu

Documentation/Home/About/News/2018/Index.rst, Documentation/Home/References.rst, Documentation/Index.rst
* "TypoScript Reference" was renamed to "TypoScript Template Reference", see
https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-Typoscript/pull/264
* We change anchor texts here to use new title
* Wherever possible we omit anchor texts, so title will always be updated
automatically in the future
Related: TYPO3-Documentation/T3DocTeam#77
Related: TYPO3-Documentation/T3DocTeam#120
Related: https://decisions.typo3.org/t/clarification-of-term-typoscript/560
=> Change links to tsref to anchor text "TypoScript Template Reference"

Documentation/Index.rst
As surf is not listed on the "Tutorials and Guides" page,
it can be removed from the main menu.
=> Remove surf from main menu

Documentation/Home/Extensions.rst, Documentation/Home/GuidesAndTutorials.rst, Documentation/Home/References.rst, Documentation/Index.rst, Documentation/Settings.cfg
- Add 1 sentence about what TYPO3 is
- Add subsections for major TYPO3 topics
- Add "Getting Started" section
- Add "How the documentation is organized"
- Add links to documentation
- Move "System extensions" to "Core documentation"
Some parts that were kept:
- get help
Some parts were removed:
- Link to "Migrate extension documentation": This link is on every
extension documentation page that was not rendered, was communicated
via email, typo3.org and TYPO3 association newsletter
- Link to typo3.org features. Once the new theme is deployed, there
will be a topbar with links to typo3.org
Resolves: #121
=> [FEATURE] Improve start page

Documentation/Home/GuidesAndTutorials.rst, Documentation/Home/References.rst, Documentation/Settings.cfg
Manuals, Guides and References are branched off to 10.4 and can be linked.
System extensions will be updated once core branches off.
ViewHelper Reference is currently missing as well.
Relates: #145
=> Update links to 10.4 where possible

Documentation/Home/References.rst, Documentation/Settings.cfg
As it is now rendered and available, matching latest available LTS.
=> Point ViewHelper Reference URLs to 10.4

Documentation/Index.rst
This commit contains changes to the Getting Started section.
The intent of this commit is to remove unnecessary content and attempt to give it a more meaningful structure and improve overall readability with new users in mind.
[+] Bullet each of the tutorials listed.
[-] Remove the composer command - this is covered in the tutorial it links to.
[+] Swap the order of the Getting Started and Site Configuration tutorial.
=> Improve readability of Getting Started section

Documentation/Index.rst
This commit features changes to the Configure TYPO3 section. The intent of this commit is to improve overall readability and also feature content that is relevant to new users.
[+] Change title by adding more context - what am I configuring?
[+] Create a consistent structure for each bullet point
[-] Remove link to ckeditor - I'd argue this is not a priority for someone new to the CMS
[+] Add link to TypoScript tutorial
=> Improve Configure TYPO3 section

Documentation/Index.rst
This commit replaces the "Create a theme" paragraph with two separate descriptions for templating and site packages with clear titles for both of these subjects.
The intent of this commit is to better signpost templating and sitepackage resources and also give a brief summary of both topics with new users in mind.
[-] Remove Theme section
[+] Create two sections with appropriate links.
[+] Add a meaningful description for backend layouts and custom content elements
[-] Remove link to fluid_styled_content - I don't think this is relevant to new users.
[-] Remove links to tsref and view helpers - not relevant to new users either.
=> Add descriptions for templating and sitepackages

Documentation/Home/GuidesAndTutorials.rst
It has been outdated since 8.7
=> Remove Extbase Guide from Menu

Documentation/Home/References.rst
If a deep link to a certain version is nessesary we
can link it from master as well. It doesn't make
sense to link to older versions.
=> [TASK] Always link to the changelog in master

Documentation/Home/OverviewInclude.rst.txt
This commit adds two new links to the Frontend Localisation Guide
[+] Add link in "Creating & Managing Content" card.
[+] Add link in "How to create translation" card.
=> [Task] Add missing link to Frontend Localisation Guide

Documentation/Home/SystemExtensions.rst
It is called "Fluid Styled Content" anywhere else
=> Call Fluid Styled Content by its name

Documentation/Home/SystemExtensions.rst
Note: (not in commit): I separated a change from the other PR - because this is unrelated. I think this will make it easier to review and merge unrelated changes, especially since some things may be up for discussion.
---
The system extension page lists documentation for system extensions.
But documenation for the most important extensions is missing (e.g. core).
This may be confusing and irritating for beginners. We explain where to
find the information for core, backend etc. ("TYPO3 Explained"), and
also refer to the "Extbase / Fluid book" for extbase and fluid.
=> Add information to sysext page

Documentation/Home/OverviewInclude.rst.txt, Documentation/Home/UpgradingTYPO3.rst
This commit adds a link to the new, much acclaimed
third-party tools section.
[+] Add card on upgrade page
[+] Add link to global nav
[+] Fix incorrect link to upgrade guide (YOLO)
=> [TASK] Add link to third-party tools section in upgrade guide

Documentation/Home/About/News/2016/Index.rst, Documentation/Home/About/News/2019/Index.rst, Documentation/Home/CreatingManagingContent.rst, Documentation/Home/OverviewInclude.rst.txt, Documentation/Home/References.rst, Documentation/Includes.rst.txt, Documentation/Index.rst, Documentation/Settings.cfg, README.rst
- align README.rst, Settings.cfg, Index.rst, Includes.rst.txt
- align intersphinx mapping names
- fix most rendering warnings
See https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument/commit/c2bb63beadb7cc1ea6eb3496613c3376f970d4c9 for further details.
Relates: https://github.com/TYPO3-Documentation/T3DocTeam/issues/181
=> [TASK] Align with new TYPO3 documentation standards

Documentation/Home/About/News/2016/Index.rst, Documentation/Home/About/News/2017/Index.rst, Documentation/Home/About/News/2018/Index.rst, Documentation/Home/About/News/2019/Index.rst, Documentation/Home/About/News/2020/Index.rst, Documentation/Home/About/UsingThisSite/Index.rst, Documentation/Home/ConfiguringTYPO3.rst, Documentation/Home/CreatingManagingContent.rst, Documentation/Home/ExtensionManuals.rst, Documentation/Home/OverviewInclude.rst.txt, Documentation/Home/References.rst, Documentation/Home/SystemExtensions.rst, Documentation/Home/Templating.rst
Relates: https://github.com/TYPO3-Documentation/T3DocTeam/issues/185
=> [DOCS] Reference manual's start page with :doc:`<manual>:Index`

Documentation/Home/ExtensionManuals.rst, Documentation/Home/ExtensionManualsSearch.rst
This moves the extension manuals search to a separate page and
thus fixes the problem with the automatic scrolling on that page.
Additionally, information is added about what the Extension Manual
Search will find and what it will not find.
Also, this patch makes the extension manual search a little less
prominent and propagates searching on extensions.typo3.org.
Both have their pros and cons, but it is very confusing for the
user to have to know if an extension provides documentation on
docs.typo3.org and currently many extensions do not.
The extension manuals search on docs.typo3.org had some drawbacks:
- automatic scrolling of extension page
- only third party extensions are shown which are rendered on
docs.typo3.org (see above)
- in some cases, the results may be incorrect (see issues) …
=> Move extension manuals search to separate page

Documentation/Home/SystemExtensions.rst
With the change from commit https://github.com/TYPO3-Documentation/DocsTypo3Org-Homepage/commit/799018686756e66de7b35300c841853a7d91b794
the tiles layout was introduced and the submenu removed. To
improve the usability the submenu is introduced again. Now
one can click on the "System Extension" menu and on the
desired manual directly again without reading and scrolling
through the tiles (which costs some more seconds).
In contrast to the previous implementation (which links to master/main),
the last stable version of a manual is linked now.
=> [TASK] Bring back system extensions submenu

Documentation/Home/SystemExtensions.rst
The documentation for reports is new and available only in v12. Reactions is a new system extensions in v12.1.
=> [TASK] Add system extensions "reactions" and "reports"

Documentation/Home/About/News/2016/Index.rst, Documentation/Home/About/News/2017/Index.rst, Documentation/Home/About/News/2018/Index.rst, Documentation/Home/About/News/2019/Index.rst, Documentation/Home/About/News/2020/Index.rst, Documentation/Home/About/UsingThisSite/Index.rst, Documentation/Home/ConfiguringTYPO3.rst, Documentation/Home/OverviewInclude.rst.txt, Documentation/Home/References.rst, Documentation/Home/SystemExtensions.rst, Documentation/Home/Templating.rst
We now use the start label again to link to start pages
Related: TYPO3-Documentation/T3DocTeam#198
=> Replace links to start page (:doc: => :ref:)

Documentation/Home/References.rst
The links go to the v11/v12 changelogs not to the LTS, this should be reflected by the linked texts.
=> [TASK] Adjust text of links for changelogs

Documentation/Home/ExtensionManuals.rst
This makes the documentation about "How to document an extension" more accessible. Just click the main navigation item or follow the links on the cards.
=> [FEATURE] Add "Document an extension" to the extensions chapter

Documentation/Home/SystemExtensions.rst
As the v12 version is now rendered successfully, we promote this version instead of main.
=> [TASK] Use v12 as reference for EXT:sys_note

Documentation/Home/SystemExtensions.rst
Additionally, fix the spelling of "Core".
EXT:t3editor is not available anymore for v13, but was merged into EXT:backend. The documentation page for 13-dev is linked to the new "Code editor" page TYPO3 Explained, so users can easily find the new documentation. With the release of 13 LTS the t3editor part can be moved down to the "abandonded" section.
=> [TASK] Add 13-dev links to "System extensions"

WebRootResources/services/VersionMatcher.php
It has been moved some time ago: https://github.com/TYPO3GmbH/site-intercept/blob/develop/legacy_hook/ajaxversions.php
(Got this info from Andi)
=> [TASK] Document new location of this file

.github/workflows/CI.yml, .github/workflows/docshome.yml
Github Marketplace action gets updated over time
and also deprecated which also counts for known
GitHub action workflows like checkout and similar.
The workflows in this repository uses already
current versions of these workflows mostely,
but not completly.
This change updates the remaining deprecated
workflow versions to the currect version. [1]
[1] https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
=> [TASK] Update borrowed action workflows

Documentation/Home/ApiTypo3Org.rst, Documentation/Home/ConfiguringTYPO3.rst, Documentation/Home/CreatingManagingContent.rst, Documentation/Home/GettingStarted.rst, Documentation/Home/References.rst, Documentation/Home/SystemExtensions.rst, Documentation/Home/Templating.rst, Documentation/Home/UpgradingTYPO3.rst, Documentation/Home/_OverviewInclude.rst.txt, Documentation/guides.xml, Documentation/mainMenu.rst.txt
The links to 13 will automatically be changed to 13.4 branches once TYPO3 13.4.0 is released and the links are changed in the render-guides. Until then the point to main
=> [TASK] TYPO3 13.4 is the new stable, 12.4 the new oldstable

Documentation/_mainMenu.rst.txt
It was merged into backend with TYPO3 13
=> [TASK] Remove main version of t3editor

Documentation/_mainMenu.rst.txt
Was integrated into TYPO3 Explained
References https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/4917
=> [TASK] Remove Upgrade Guide from Menu

Documentation/Index.rst, Documentation/_mainMenu.rst.txt
Adds a main card on the start page to Fluid, adds it to the menu. Fixes a small typo/oddity in the "ViewHelper" section.
=> [TASK] Add links to typo3fluid/fluid main reference
