TYPO3-Documentation/DocsTypo3Org-Homepage

- Documentation/typo3cms/Index.rst
- Documentation/typo3cms/References/Index.rst
> [FEATURE] Link TYPO3 CMS Changelog where people expect to find it

- Documentation/typo3cms/GuidesAndTutorials/Index.rst
> [TASK] Change order for tutorials

- Documentation/typo3cms/References/Index.rst
> [FEATURE] Add descriptions and additional links to References

- Documentation/typo3cms/GuidesAndTutorials/Index.rst
- add an additional column "category"
- add descriptions for all manuals
- change column "Comment" to "Description"
> [FEATURE] Add description to manuals on Guides & Tutorials

- Documentation/Contribute/Index.rst
- Add Github method as method for contributing and add link
- Add link to YouTube video for contributing to docs
Resolves: #40
> [FEATURE] Add link to git / docker method and YouTube video

- Documentation/Index.rst
> Do not use buttons as links

- Documentation/Index.rst
- Change link to tips
- Add links to news on typo3.org
> Some changes on start page

- Documentation/Home/Teams.rst
Motivation is explained in issue.
Additionally, "Teams @ Work" is explained.
Resolves: #32
> Change team page to include information for general public

- Documentation/Index.rst
This commit contains several small changes to the homepage.
[+] Rename the word "Tips" from the Did You Know heading 
[+] Move the Did You Know heading so that it sits directly above its content
[+] Improve readability of the New To TYPO3 section
> Improve readability of Home page

- Documentation/Home/References.rst
- Documentation/Settings.cfg
Related: https://github.com/TYPO3-Documentation/T3DocTeam/issues/97
> Fix links on reference page

- Documentation/Home/About/UsingThisSite/Index.rst
... until search integration.
Even if only a few people see this, it shows that we care. Sometimes little things can tip the scale from people just being frustrated and people wanting to contribute ...
> Add notice for problem with search

- Documentation/Home/SystemExtensions.rst
- remove rsaauth and taskcenter from quick links
- use new URL schema (this also fixes broken link for SEO)
> Clean up list of system extensions

- Documentation/Home/GuidesAndTutorials.rst
- Documentation/Settings.cfg
Change URL to ref inside guide and tutroials
> Fix ref for Templating Tutorial

- Documentation/Home/SystemExtensions.rst
Resolves: https://github.com/TYPO3-Documentation/T3DocTeam/issues/108
> Add link to func docs in list of dropped sysexts

- Documentation/Home/About/News/2019/Index.rst
- Documentation/Home/WhatsNew.rst
- Documentation/Index.rst
This covers:
- a link to the "What's New Slides"
- changelog and extension scanner
- new documentation
> Add "What's new" section

- Documentation/Home/About/News/2020/Index.rst
discussion instead of dicussion
> minor spelling mistake

- Documentation/Home/About/Index.rst
- Documentation/Home/Contribute.rst
- Documentation/Home/GuidesAndTutorials.rst
- Documentation/Home/References.rst
- Documentation/Home/SystemExtensions.rst
- Documentation/Index.rst
> [TASK] Remove arrows from menus

- Documentation/Index.rst
This commit is intended to improve the overall readability of the documentation landing page by making minor changes
to sentence strucutre in certain areas of the page.
> Improve readability of documentation homepage

- Documentation/Index.rst
This commit contains changes to the "How the documentation is organized" section. The intent of this commit is to improve its general readability with new users in mind.
[+] Attempt to create a consistent structure for each bullet point.
[+] Have only one link to per bullet point.
> Improve readability of Documentation overview section

- Documentation/Home/WhatsNew.rst
Related: TYPO3-Documentation/T3DocTeam#146
> Fix information about master branch

- Documentation/Home/SystemExtensions.rst
I guessed a lot of this. It didn't make much sense to me. Please let me know if I didn't get it right.
> Add admpanel to Docs TOC

- Documentation/404.rst
Fixes: https://github.com/TYPO3-Documentation/t3docs-search-indexer/issues/20
> Mention global search on 404 page

- Documentation/Home/SystemExtensions.rst
> Add system extensions

- Documentation/Home/CreatingManagingContent.rst
This commit adds a deep linking card to the Creating
& Managing Content page
[+] Add card
[+] Adjust font size for all card titles
> [TASK] Add deep linking card

- WebRootResources-api.typo3.org/index.html
Additionally update to latest menu structure
and used theme.
> [TASK] Update master<>main links

- Documentation/Home/SystemExtensions.rst
Resolves: #177
----
Not in commit:
Rendered result:
> Add card layout to system extensions

- Documentation/Home/References.rst
Additionally, adjust 12-dev links to main path to
avoid redirect from master.
> [TASK] Add link to changelog for version 12

- Documentation/Home/About/News/2020/Index.rst
- Documentation/Home/CheatSheets.rst
- Documentation/Home/ConfiguringTYPO3.rst
- Documentation/Home/Contribute.rst
- Documentation/Home/CreatingManagingContent.rst
- Documentation/Home/ExtensionManuals.rst
- Documentation/Home/GettingStarted.rst
- Documentation/Home/SystemExtensions.rst
- Documentation/Home/Templating.rst
- Documentation/Home/UpgradingTYPO3.rst
- Documentation/Index.rst
> [TASK] Link to main branch of docs where appropriate

- .github/workflows/CI.yml
Additionally, use the latest version.
> [CI] Use docker image from ghcr.io

- Documentation/Home/SystemExtensions.rst
- Remove 10.4 links
- Add 12.4 links
> [TASK] Adjust version links for system extension manuals

- Documentation/Home/SystemExtensions.rst
Adding main  version for now as the 12.4 only displays the README content until the next release
> Add system notes to the system extension

- Documentation/Home/SystemExtensions.rst
Also remove very old versions from the table, they can be found on packagist
> [TASK] Replace outdated syntax

- Documentation/Home/Contribute.rst
- Documentation/Home/Overview.rst
- Documentation/Home/SystemExtensions.rst
- Documentation/Index.rst
* Fix some broken links and labels in a drive-by
> [TASK] List all official documentation resources

- Documentation/guides.xml
Resolves: https://github.com/TYPO3-Documentation/DocsTypo3Org-Homepage/issues/250
> [TASK] Disable Version Switch

- Documentation/_mainMenu.rst.txt
And fix errors in Headlines wrongly linked
> Add api.typo3.org to the menu

- Documentation/Home/RecentlyMovedChapters.rst
- Documentation/_mainMenu.rst.txt
We always call it this when we are talking about it
> [TASK] Call How to Document by this name

- WebRootResources/llms.txt
- Outlines allowed paths for large language model crawlers
- Provides licensing context (CC-BY-SA, GFDL, Open Publication License)
- Ensures equal access for all major AI bots (GPTBot, ClaudeBot, etc.)
- Lists recommended paths and exclusions for accurate crawling
> [TASK] Add llms.txt for LLM crawler guidance
